### PR TITLE
Fix closing animation bug

### LINKED ISSUE #311: Null check error during animateToClosed
**Describe the bug**
Crashlytics error report. No idea what the actual implication of this is. Probably something breaks on the close animation, but that shouldn't affect functionality.

**Stacktrace**
_What's the stacktrace?_

> Non-fatal Exception: FlutterError
> 0  ???                            0x0 _WiredashBackdropState._animateToClosed + 983 (wiredash_backdrop.dart:983)
> 1  ???                            0x0 BackdropController.animateToClosed + 1209 (wiredash_backdrop.dart:1209)
> 2  ???                            0x0 WiredashModel.hide + 128 (wiredash_model.dart:128)
> 3  ???                            0x0 PsModel.returnToAppPostSubmit + 129 (ps_model.dart:129)
> 4  ???                            0x0 PsModel.submit + 124 (ps_model.dart:124)

**Wiredash SDK Info**
_Which SDK are you using?_
^1.7.4

_On which platform are you seeing the crash?_
iOS (was the only platform checked, probably also happens on Android)

**Flutter SDK**
_Which Flutter version are you using? Run `flutter doctor -v`_

> [✓] Flutter (Channel stable, 3.13.4, on macOS 14.1.1 23B81 darwin-arm64, locale de-DE)
>     • Flutter version 3.13.4 on channel stable at /Users/ciriousjoker/fvm/versions/3.13.4
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 367f9ea16b (2 months ago), 2023-09-12 23:27:53 -0500
>     • Engine revision 9064459a8b
>     • Dart version 3.1.2
>     • DevTools version 2.25.0

**Screenshots**

### PR DESCRIPTION
**Pull request by passsy**
Fixes https://github.com/wiredashio/wiredash-sdk/issues/311

### CODE REVIEW

File: test/feedback_flow_test.dart [hunk 1]
```diff
@@ -442,6 +444,46 @@ void main() {
       expect(submittedFeedback!.labels, ['lbl-1', 'lbl-2']);
       expect(submittedFeedback.message, 'feedback with labels');
     });
+
+    testWidgets('spam tap during close animation', (tester) async {
```
Comment (ciriousjoker) [inline test/feedback_flow_test.dart:448]: lol I was wondering what our users had been doing

Comment (passsy) [reply test/feedback_flow_test.dart:448]: This was my first prediction. But the actual bug happened only after swiping first
